const productos = [
    {
    id: 1,
    ref: "Teclado",
    marca: "Redragon",
    modelo: "Yama K550 RGB White Mecánico",
    precio: 8170,
    img: "./img/Teclado - Yama K550.png",
  },
  {
    id: 2,
    ref: "Teclado",
    marca: "Logitech",
    modelo: "G Pro Kda RGB",
    precio: 13990,
    img: "./img/Teclado - G Pro Kda.png",
  },
  {
    id: 3,
    ref: "Teclado",
    marca: "Corsair",
    modelo: "K70 RGB MK.2 RapidFire",
    precio: 21490,
    img: "./img/Teclado - K70.jpg",
  },
  {
    id: 4,
    ref: "Mouse",
    marca: "Philips",
    modelo: "G403 RGB",
    precio: 1290,
    img: "./img/Mouse - G403.png",
  },
  {
    id: 5,
    ref: "Mouse",
    marca: "HperX",
    modelo: "PulseFire Core RGB",
    precio: 1595,
    img: "./img/Mouse - PulseFire.jpg",
  },
  {
    id: 6,
    ref: "Mouse",
    marca: "Logitech",
    modelo: "G G502 LightSpeed",
    precio: 9990,
    img: "./img/Mouse - G G502 LightSpeed.png",
  },
  {
    id: 7,
    ref: "Auricular",
    marca: "HyperX",
    modelo: "Cloud Core Pc 7.1",
    precio: 8499,
    img: "./img/Auricular - Cloud Core.jpg",
  },
  {
    id: 8,
    ref: "Auricular",
    marca: "Corsair",
    modelo: "Virtuoso RGB",
    precio: 26990,
    img: "./img/Auricular - Virtuoso.png",
  },
  {
    id: 9,
    ref: "Auricular",
    marca: "Redragon",
    modelo: "H260 Hylas RGB",
    precio: 2999,
    img: "./img/Auricular - Hylas.png",
  },
  {
    id: 10,
    ref: "Notebook",
    marca: "Gigabyte",
    modelo: "Aero 15 Oled I7 11800H RTX3080P",
    precio: 440990,
    img: "./img/Notebook - Gigabyte.jpg",
  },
  {
    id: 11,
    ref: "Notebook",
    marca: "Banghó",
    modelo: "Max L5 I7 1051OU 15.6'",
    precio: 109990,
    img: "./img/Notebook - Bangho.jpg",
  },
  {
    id: 12,
    ref: "Notebook",
    marca: "Lenovo",
    modelo: "CloudBook 2 en 1 Celeron N4020 10'",
    precio: 54990,
    img: "./img/Notebook - Lenovo.jpg",
  },
  {
    id: 13,
    ref: "Monitor",
    marca: "Samsung",
    modelo: "T350H FHD IPS 5ms 75Hz",
    precio: 25990,
    img: "./img/Monitor - Samsung.png",
  },
  {
    id: 14,
    ref: "Monitor",
    marca: "Gigabyte",
    modelo: "Aorus FI27Q-PSA IPS QHD 1ms",
    precio: 139990,
    img: "./img/Monitor - Gigabyte.jpg",
  },
  {
    id: 15,
    ref: "Monitor",
    marca: "LG",
    modelo: "UltraFear 32GN500-B FullHD 165Hz 1ms",
    precio: 67999,
    img: "./img/Monitor - LG.png",
  },
];

// Array de objetos con los medios de pagos y respectivos descuentos.
const medioDePago = [
  {
    ref: "EF",
    medioPago: "Efectivo",
    descuento: 25,
  },
  {
    ref: "TC",
    medioPago: "Tarjeta de Crédito",
    descuento: 15,
  },
  {
    ref: "DEB",
    medioPago: "Tarjeta de Débito",
    descuento: 10,
  },
];

export {
  productos,
  medioDePago
}